version: "3"
services:
  mongo:
    image: mongo:latest
    ports:
      - "20717:20717" 
    volumes:
      - /data/db # Create a volume for the DB.
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    env_file: 
      - ./client/.env
    restart: always
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo
    env_file: 
      - ./server/.env
    ports:
      - "4000:4000"
    restart: always